- miniz_tdef.c
Fixed array index where to store image height.
PNG files made using `tdefl_write_image_to_png_file_in_memory_ex()` were very tall, with a huge empty area at the end.
Since `pnghdr[22]` was assigned twice, I changed indices to store height exactly in the way width is stored (two consecutive swapped bytes). Now PNG file height is correct.
> Fix PNG height

- miniz_zip.c
- miniz_zip.h
- tests/miniz_tester.cpp
Hi,
Great little library, been using it for some prototyping on an embedded platform recently.
Had a need to extract large files (3-5MB...on an embedded system) from a zip directly to a waiting web server client.
Callback method was a good start but network stack memory usage became an issue.
Therefore I've written an iterative decompression method, allowing a file to be decompressed in variable sized chunks - allowing me to load small chunks at a time into my socket as the TCP buffers empty.
I've based it heavily on the callback method.
A state instance (containing the variables which were on the stack before with the callback extractor) can be created with mz_zip_reader_extract_iter_new or mz_zip_reader_extract_file_iter_new.
Once constructed the compressed file can be read either …
> Iterative decompression

- miniz_zip.c
Was returning on error without closing file or storing file handle anywhere.
Error was caught by Coverity Scan static analyzer while scanning my project OpenKJ.
Apologies if this was by design and I missed it.
> Fix resource leak in mz_zip_reader_init_file_v2

- miniz_zip.c
Issue #81
As MZ_DEFAULT_COMPRESSION is set as "-1", one of the bits is incorrectly
interpreted as the "MZ_ZIP_FLAG_COMPRESSED_DATA" flag before the check
for (flags < 0) intended to catch the MZ_DEFAULT_COMPRESION case.
This would then cause an assert() to be hit on any calls where the
uncomp_size is non-zero.
Moving the "Default" level check above any other flag checks should
solve this issue.
> Fix assert with mz_zip_writer_add_mem* w/MZ_DEFAULT_COMPRESSION

- miniz_zip.c
Under Windows _stat maps to _stat64i32 which only supports max int32_t file sizes.
Change to _stat64 which uses 64bit file sizes and file modification times.
> Fix large file support under Windows

- miniz_zip.c
Hi.  While trying to make [C-Blosc2](https://github.com/Blosc/c-blosc2) as free of warnings as possible I fixed a fall-through warning in miniz (2.0.8) that only shows up in MSVC (at least 2013 and 2015 versions) when compiling in 32-bit mode (in 64-bit the issue does not show-up). The root of the problem seems to be that in this mode, `size_t` is 32-bit and receiving data from `mz_uint64` may result in a 'data loss'.
I think the warning is meaningful.  In case you don't think this represents an actual issue, this PR just does a cast for making the warning go away.
> Fix a MSVC 2013 warning

- miniz_zip.c
This is another set of fixes for warnings in MSVC (2019, but maybe in others too).
> More fixes for warnings MSVC

- miniz.h
Add !defined check so that one can override by defining MINIZ_USE_ALIGNED_LOADS_AND_STORES in case a given compiler does not support it (this issue has been seen in the wild, see assimp/assimp#2389)
There isn't a contribution guide that I can find; please let me know if there's anything you want me to change. Also, I'm still testing this, but I can't imagine this compiler guard will cause issues.
> Add !defined check on MINIZ_USE_ALIGNED_LOADS_AND_STORES

- CMakeLists.txt
- amalgamate.sh
- examples/example2.c
- examples/example4.c
I wanted to generate the single `miniz.h` header in a cross-platform way, so I rewrote the amalgamation step in CMake. I also added options to toggle whether the build should proceed normally, use the amalgamated sources, or build the header-only version.
Examples that depended on the various individual headers I changed to depend on `miniz.h`, since they will fail to build when amalgamation or header-only options are specified.
To ensure the amalgamation logic is only in one place, I replaced the code from `amalgamate.sh` to use the CMake variant.
I will have a follow-up PR to set up the `EXPORT` file.
PTAL @uroni
> CMake updates and CMake-based amalgamation step

- CMakeLists.txt
- Config.cmake.in
Hello there,
I've extended the cmake script to be able to build a shared library with properly exported symbols with gcc and msvc. It creates the cmake config file in the standard way for find_package to be usable when importing the miniz library to other projects.
> Modified cmake script to support shared library mode and find_package.

- CMakeLists.txt
- miniz_zip.h
One last pull request as I'm a bit concerned about forcing _GNU_SOURCE in header only mode. It might cause problems if a user would not like it to be defined. If explicit large file support is desired, one can still define _LARGEFILE64_SOURCE before including miniz.h (applies for header only amalgamated version).
Currently the include location after installing is <miniz/miniz.h>. I've included a small fix to make it work with <miniz.h> as well.
I also included a tiny fix for a doc comment which caused me a bit of confusion.
> Add include location tolerance and stop forcing _GNU_SOURCE

- miniz_zip.h
Simple fix to make the header clearer, matching the c file.
> mz_zip_reader_locate_file_v2 returns an mz_bool

- miniz_zip.c
Code should check for__USE_LARGEFILE64, not _LARGEFILE64_SOURCE
_LARGEFILE64_SOURCE should be used only for setting a preference
when compiling code (either explicitly or by the compiler itself).
Then, according to its value, features.h will take care of defining things
like __USE_LARGEFILE64 appropriately.
As a side-effect, this patch adds support for clang. When building
with clang one has to explicitly define _LARGEFILE64_SOURCE if he
wants to use the *64 api.
> Fix LFS check

- miniz.c
Adds '#elif defined(USE_EXTERNAL_MZCRC)' by the mz_crc32() definition
to enable the option of a user linking in an alternate crc implementation.
The main reason why this might be desired would be to use an SSE-accelerated
crc implementaiton, which would be faster, but not be reasonable to include
in this file.
> Add #elif to enable an external mz_crc32() to be linked in.

- miniz_zip.c
This fixes a warning for an unused variable if `MINIZ_DISABLE_ZIP_READER_CRC32_CHECKS` is on.
> Fix missing crc guard

- miniz_zip.c
GCC ANSI mode fails to compile since `//` style comment is not supported in ANSI mode.
```
...
Test compile with GCC ANSI...
_build/amalgamation/miniz.c:3053:35: error: operator '/' has no right operand
#elif defined(__USE_LARGEFILE64) // gcc, clang
...
```
This PR uses old C style comment to fix it.
> ansi mode does not support double-slash comment. 

- CMakeLists.txt
- tests/checksum_fuzzer.c
- tests/flush_fuzzer.c
- tests/fuzz_main.c
- tests/ossfuzz.sh
- tests/uncompress_fuzzer.c
This PR adds multiple fuzz targets for [OSS-Fuzz integration](https://google.github.io/oss-fuzz/architecture/) to automate fuzz testing for this project. Once integrated issues will be automatically filed on bugs.chromium.org when bugs are found and closed when they're fixed.
The project has already been [accepted](https://github.com/google/oss-fuzz/pull/3650) for integration.
The fuzz targets have been integrated into the CMake build with a new `BUILD_FUZZERS` option (defaults to OFF), this can be used to reproduce test cases when built with sanitizers (by setting `CFLAGS=-fsanitize=address`).
If this PR is accepted I would handling the rest of the integration, if all goes well a second PR would be made to add a few more fuzzers (e.g. a zip fuzzer similar to `tests/miniz_tester.cpp`). …
> Add fuzz targets for OSS-Fuzz integration

- miniz_tinfl.c
It is use-of-uninitialized values because it is copying bytes from the output buffer which hasn't been written to yet. In, `tinfl_decompress` when copying the `counter` number of bytes in the loop the first time around, `pOut_buf_cur == pSrc == pOut_buf_start`. It may require `MINIZ_USE_UNALIGNED_LOADS_AND_STORES` and `MINIZ_UNALIGNED_USE_MEMCPY` to be turned off.
Here is the memory sanitizer error:
```
==60017==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x4c6842 in tinfl_decompress /home/nathan/Source/miniz/build/../miniz_tinfl.c:641:13
#1 0x4a2d4f in mz_inflate /home/nathan/Source/miniz/build/../miniz.c:466:18
#2 0x4a8103 in mz_uncompress2 /home/nathan/Source/miniz/build/../miniz.c:574:14
#3 0x4a8c1d in mz_uncompress /home/nathan/Source/miniz/build/../miniz.c:588:12
#4 …
```
> Fixed use-of-uninitialized value msan error when copying dist bytes

- miniz.h
According to ChangeLog.md Zip64 format is supported since 2.0 release
> Correct zip64 ZIP archive support limitations entry

- .github/workflows/ci-fuzz.yml
This adds a GitHub Action to PR's to verify code changes do not introduce new bugs or cause the OSS-Fuzz build to break.
For more info: https://google.github.io/oss-fuzz/getting-started/continuous-integration/
> Integrate with CIFuzz (OSS-Fuzz)

- tests/zip_fuzzer.c
Turns out this an unbounded operation vulnerable to decompression bombs.
> zip_fuzzer: omit file validation

- miniz_zip.c
Not all codepath were freeing the buffer before returning.
https://oss-fuzz.com/testcase?key=5744008051294208
> mz_zip_validate_file(): fix memory leaks

- miniz.h
There is a small typo in miniz.h.
Should read `purposely` rather than `purpsosely`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, purpsosely -> purposely

- miniz_tinfl.c
In this instance `dist` was 31 which `s_dist_base` translates as 0 since the last two entries in the `s_dist_base` is 0.
https://github.com/richgel999/miniz/blob/d6566206ce120069708e77eff79cf117957b419a/miniz_tinfl.c#L490-L492
https://oss-fuzz.com/testcase-detail/4863557237473280
This has also been submitted as Blosc/c-blosc2#215.
> Fixed MSAN use-of-uninitialized in tinfl_decompress when invalid dist.

- miniz_zip.c
When NDEBUG, the assert in mz_zip_array_range_check does nothing and an unused variable warning is generated at https://github.com/richgel999/miniz/blob/4159f8c8c3d91a76648107ce6adf54bb6f06e3a7/miniz_zip.c#L280
This PR removes the `|| define (NDEBUG)` so when debugging is turned off, no range check is performed.
> Fix unused parameter ‘pArray’ in mz_zip_array_range_check

- miniz_zip.c
- miniz_zip.h
the api required to know the size before writing the file. i didn't see a reason for this limitation and removed it.
> write with dynamic size

- CMakeLists.txt
- Added code to determine whether this is a standalone project or included by other projects.
- Added option ```INSTALL_PROJECT``` to enable/disable install project.
- Replaced ```CMAKE_BINARY_DIR``` to ```CMAKE_CURRENT_BINARY_DIR```.
> Improved cmake subproject support

- ChangeLog.md
- readme.md
This PR fixes two broken links in `readme.md` and corrects one typo in `ChangeLog.md`.
> readme.md: fix broken links

- miniz_tdef.c
In `tdefl_record_literal`, the following expression may read an uninitialized value in the `m_pLZ_flags` field:
*d->m_pLZ_flags = (mz_uint8)(*d->m_pLZ_flags >> 1);
By explicitly initializing the field, we avoid possible undefined behaviors.
Issue found with Frama-C.
> avoid use of uninitialized value in tdefl_record_literal

- CMakeLists.txt
Little change to make fetched miniz work as subproject. Same check is used in multiple projects i.e. Catch2.
> Make cmake recognize FetchContent subproject

- miniz_tdef.c
L#1067 asserts that (match_len >= TDEFL_MIN_MATCH_LEN)
> remove redundant condition

- miniz_zip.c
`mz_freopen`, `mz_fopen` and `_stat64` will fail if the path or filename contains unicode characters.
Converting the input strings to widechar arrays first would prevent such issues.
> Support for unicode characters in paths and filenames on windows

- miniz_zip.c
Fix MinGW cross compilation by removing unneeded capitalization. Fixes #205
> Fix MinGW cross compilation by removing unneeded capitalization

- miniz_tinfl.c
This patch comes from https://github.com/libxmp/libxmp/pull/436#issuecomment-884977962
> Fix use of uninitialized memory in tinfl_decompress_mem_to_callback()

- miniz_tinfl.c
Fixes: https://github.com/richgel999/miniz/issues/216
Also see:
https://github.com/mitkus/miniz/commit/6b8c30e4a95dd649adf14cf4bcad90701e323b9a
> tinfl_decompress: avoid NULL ptr arithmetic UB:

- miniz_tinfl.c
- miniz_tinfl.h
The Huffman tables are dimensioned after the biggest one (288) but that wastes a lot of memory for the other two which are considerably smaller (32 and 19). This PR creates separate arrays with proper lengths.
> Reduce memory usage for inflate

- miniz_zip.c
As per comment in https://github.com/richgel999/miniz/blob/842a20e5867345db94162c8dec8ff941bc06e9d6/miniz_zip.h#L117
Fixes issue #223, compiling with `-Werror=switch-enum`.
> Add switch case for MZ_ZIP_TOTAL_ERRORS

- miniz_tdef.c
FLEVEL is a 2-bit value in the zlib header, an estimate of the compression level, miniz always writes `0` for this field.
This PR changes the value of FLEVEL from `0` to values between `0` and `3` based on compression level and computes the header checksum (FCHECK).
The compression level -> FLEVEL value mapping is based on zlib: https://github.com/zlib-ng/zlib-ng/blob/v1.2.11/deflate.c#L816-L829
Tested with compression level values `-1` (zlib `Z_DEFAULT_COMPRESSION`) through 11.
> deflate: write zlib FLEVEL based on compression level

- miniz_zip.c
FreeBSD does not have and does not need fopen64 and friends - base functions have 64 bit offset support.
> Fix compatibility with FreeBSD and improve readability in miniz_zip.c

- CMakeLists.txt
- miniz.pc.in
`/usr/share/pkgconfig` should be used for architecture independent libraries (e.g. data or scripts), while an architecture dependent directory like `/usr/lib64/pkgconfig` should be used for native binaries.
Also set the include path to allow users to include `<miniz.h>` instead of `<miniz/miniz.h>` which seems to be the intended behaviour.
> pkg-config tweaks

- miniz_zip.c
Hi! I've been fuzzing your project inside pyTorch via model load and found integer overflow error in check for header corruption. The problem is that header may be corrupted or invalid, but because of overflow the check might succeed.
Here is output of sanitizers:
/pytorch_fuzz/third_party/miniz-2.0.8/miniz.c:3654:41: runtime error: unsigned integer overflow: 4294967295 * 46 cannot be represented in type 'unsigned int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /pytorch_fuzz/third_party/miniz-2.0.8/miniz.c:3654:41 in
Here is a warning of our tool, which works together with fuzzer, which found an error:
[2022-05-20 12:09:01.642076] [info] [security]   mz_zip_reader_read_central_dir:/pytorch_sydr/third_party/miniz-2.0.8/miniz.c:3654 - imul ecx, eax, 0x2e - unsigned integer …
> Fix integer overflow in header corruption check.

- miniz_tdef.c
Building with extended warnings and -Werror produces a fail b/c n shadows previous declaration. See line 630 vs 613 of miniz_tdef.c
> Fix for n shadows variable

- miniz_tinfl.c
Fixing VS warning:
`[C4334] '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)`
> Bit shift fix

- miniz_tdef.c
Broken after https://github.com/richgel999/miniz/commit/e7d0e216d5288c24bbb85527808b7bf4794bfaba and https://github.com/richgel999/miniz/commit/bc77ea10177576ca8587868b87a372225670ded9
> Fix variable declaration.

- miniz_tinfl.c
- miniz_zip.c
When adding multiple mz_uint32 values (or a mix of mz_uint32 and mz_uint64 values) to a mz_uint64 value, the mz_uint32 values should be promoted to mz_uint64 before the addition is done. To ensure this is the case, the mz_uint64 value should be placed first, or, if all values are mz_uint32, then the first one should be cast to mz_uint64.
> Ensure correct integer promotion when adding

- miniz_zip.c
Miniz started including windows.h from version 3.0.0 and on when compiling for Windows using MSVC.
windows.h header file is known to conflict with C++ std namespace by defining its own min/max macros. It is a common practice to disable these ancient macros in windows.h by declaring NOMINMAX macro prior to including windows.h in code.
While this issue does not affect miniz directly due to the fact that it is straight-C code and it does not use min/max from C++ std namespace, it does affect other projects like miniz-cpp which wrap and amalgamate miniz and then both compile in C++ mode and use min/max from std namespace.
It is therefore proposed to prefix inclusion of windows.h in miniz_zip.c by the following lines:
```
#ifndef NOMINMAX
#define NOMINMAX
#endif
```
> Prevent min/max conflicts between windows.h and std namespace 

- miniz.h
The version number in the title comment (line 1) was not updated since version 3.0.0, which causes confusion between versions 3.0.0, 3.0.1 and 3.0.2. It would be good if the title comment in this header file was updated for each release as it is exactly that this comment is being looked at by most programmers when checking the library version in their code trees.
> Update miniz.h to correctly reflect release version in the title comment

- miniz_tdef.c
Merged definition of static const mz_uint s_tdefl_num_probes[11] with its declaration to avoid compilation error when compiling in forced-C++mode
When miniz_tdef.c is compiled in C++ mode (either by forcing the compiler to treat the input as C++ or by renaming the file into miniz_tdef.cpp), MSVC17 produces the following error:
> miniz_tdef.cpp(2113,22): error C2086: 'const mz_uint s_tdefl_num_probes[11]': redefinition
> miniz_tdef.cpp(1254,22): message : see declaration of 's_tdefl_num_probes'
This happens because in miniz_tdef.c we have the following:
```
/*Line 606:*/ static const mz_uint s_tdefl_num_probes[11];
/*Line 1465:*/ static const mz_uint s_tdefl_num_probes[11] = { 0, 1, 6, 32, 16, 32, 128, 256, 512, 768, 1500 };
```
Such construct is legal in C, but not legal in C++. While …
> Update miniz_tdef.c to enable compiling in forced-C++ mode

- miniz_zip.c
Pragmatic approach: Treat Linux on x86_64 the same as Mac OS X and FreeBSD, i.e. as a Unix-like 64-bit operating system with known large file support.
Fixes #257
> Fix missing large file support warning on 64-bit Linux

- CMakeLists.txt
`Compatibility with CMake < 3.5 will be removed from a future version of CMake`
Nothing much, just to fix warning in recent CMake versions.
> Bump cmake minimum version

- miniz_tinfl.c
Remove parameter check in tinfl_decompress() that breaks tinfl_decompress_mem_to_heap() as a follow up to the discussion on pull request #268
> Remove parameter check in `tinfl_decompress` that breaks `tinfl_decompress_mem_to_heap`

- miniz_zip.c
This line clashes with other libraries such as [bdwgc](https://github.com/ivmai/bdwgc) or [sokol](https://github.com/floooh/sokol); while they only define the macro if it hasn't been defined before, miniz always `#define`s, which can cause compilation warnings.
> Don't redefine `WIN32_LEAN_AND_MEAN` if already defined

- miniz_zip.c
Zip archives are usually read from the back to the front, making it possible to append them to other files (e.g. executables) in order to provide some kind of embedded filesystem.
We can actually extract the start of the archive by looking at the central directory offset, by comparing the specified and the actual file offset.
The Zip64 format adds another challenge as the EOCD locator specifies the offset to the EOCD starting from the beginning of the archive. Such relative offset cannot be directly used for archives not starting at position zero, hence the addition of another step that tries to locate the 64bit EOCD right before the EOCD locator. The added overhead is pretty small (and could be made smaller by reading both the presumed EOCD and EOCD locator at once) and works pretty well …
> Support Zip archives not starting at zero offset

- miniz_zip.c
The first commit fixes a silly oversight in the freshly-added code, the fuzzer found the problem in no time.
The second commit is slightly different as it prevents the user error to some degree, the `mz_zip_mem_read_func` function doesn't use the `m_file_archive_start_ofs` field and am not sure if it should. So this commit prevents the new machinery from changing the offset/size of the archive, if you feel the problem should be solved in another way (e.g. taking `m_file_archive_start_ofs` into account) I'll amend the PR asap.
> Two small fixes

- CMakeLists.txt
- tests/add_in_place_fuzzer.c
This new fuzzer implementation targets the `mz_zip_add_mem_to_archive_file_in_place` function. The hardcoded `/tmp` path works fine for the OSS-Fuzz platform, as `/tmp` is [the only writable directory available](https://google.github.io/oss-fuzz/further-reading/fuzzer-environment/#file-system). However, it won’t be compatible with Windows environments, where `/tmp` doesn’t exist. I’m not certain if anyone is running these fuzzers on Windows.
> Add fuzzer for mz_zip_add_mem_to_archive_file_in_place function

- .github/workflows/ci-fuzz.yml
- miniz_tinfl.c
This was originally reported in #90 which was closed without any remediation. 
This can be reproduced by downloading the POC from here:
https://github.com/Edward-L/my-cve-list/blob/master/miniz/dos-an-infinite-loop-miniz_tinfl-c-398.poc
Uncomment the `assert` in the `miniz_tinfl.c` line 494, build the project.
And then run the `example3.exe` as shown with debugger:
```
example3.exe d, "C:\Temp\dos-an-infinite-loop-miniz_tinfl-c-398.poc" "C:\Temp\Bad.txt"
```
Because the POC file used as the input is not a valid zip file, we should not be attempting to extract it. However, as a guard against other zip files that may be maliciously crafted, we've added the condition  and throw an error if both `sym2` and `counter` are zero.
> Remedy CVE-2018-12913

- CMakeLists.txt
Commit 05ab4dc05c9d1e1f951f5849b659e2c7e291a620
"Add some catch2 tests" dropped that C flag,
but should instead only have added a simple
enable_language call for tests only.
> CMakeLists.txt: only require a C compiler

- CMakeLists.txt
The prior version check assumed a major version of 3, which naturally means it failed with the new CMake v4.0. This updates the check to now properly consider the full version number, and allow usage with CMake 4.0 and later.
> fix: use more complete version test for CMake < 3.12
